security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$irALafAnxKfico21r6W41.N61VBl2a.qRF7S/MIH1MBkYZlT1x1Vm
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        secured_area:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
